name: bundle version 17.0-1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: test file
      run: |
        wget 'https://get.enterprisedb.com/postgresql/postgresql-17.0-1-windows-x64-binaries.zip'
        unzip postgresql-17.0-1-windows-x64-binaries.zip
        # ectracted to pgsql folder
        mkdir pg
        cp -r pgsql/include/libpq pg
        cp pgsql/include/libpq-fe.h pg/libpq
        cp pgsql/include/pg_config_ext.h pg/libpq
        cp pgsql/include/pg_config.h pg/libpq
        cp pgsql/include/postgres_ext.h pg/libpq
        mkdir pg/win64
        cp pgsql/bin/libpq.dll pg/win64
        # copy need files
    
    - name: Push
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: 17.0-1 # The branch name where you want to push the assets
        FOLDER: pg # The directory where your assets are generated
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
        MESSAGE: "Build: ({sha}) {msg}" # The commit message